### ISSUE TITLE
install trouble

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/RearWindow#6]
FYI only: I had a lot of problems loading this, I got some variation on the error attached for "digest" and "fs". Install the package before running install_github seemed to do the trick

![image](https://user-images.githubusercontent.com/8836685/49116713-7a79ea00-f26c-11e8-8eb5-dcc7ddfb7b7c.png)

**Comment by achafetz** [comment]
@jaliasd installed missing packages to fully install RearWindow
